[project]
name = "dashboard"
version = "0.1.0"
description = "Example of a dashboard using streamlit"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.38.13",
    "duckdb>=1.2.2",
    "matplotlib>=3.10.3",
    "seaborn>=0.13.2",
    "streamlit>=1.45.0",
    "streamlit-aggrid >= 0.5.1",
    "streamlit-echarts >= 0.4.0"
]
